In [ ]:
import pandas as pd

df = pd.read_csv('/content/risk_classification_dataset.csv')

df.head()

   age  sex     bmi  children  smoker  region      charges risk_level
0   19    0  27.900         0       1       3  16884.92400  High Risk
1   18    1  33.770         1       0       2   1725.55230   Low Risk
2   28    1  33.000         3       0       2   4449.46200   Low Risk
3   33    1  22.705         0       0       1  21984.47061  High Risk
4   32    1  28.880         0       0       1   3866.85520   Low Risk

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['risk_level_encoded'] = le.fit_transform(
    df['risk_level']
)

df[['risk_level','risk_level_encoded']].head()

  risk_level  risk_level_encoded
0  High Risk                   0
1   Low Risk                   1
2   Low Risk                   1
3  High Risk                   0
4   Low Risk                   1

In [ ]:
X = df[
    [
        'age',
        'sex',
        'bmi',
        'children',
        'smoker',
        'region'
    ]
]

y = df['risk_level_encoded']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

risk_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

risk_model.fit(
    X_train,
    y_train
)

RandomForestClassifier(n_estimators=200, random_state=42)

In [ ]:
y_pred = risk_model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(
    y_test,
    y_pred
)

print(
    "Accuracy:",
    accuracy
)

Accuracy: 0.9029850746268657

In [ ]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

           0       0.92      0.85      0.88        92
           1       0.90      0.93      0.92        88
           2       0.89      0.93      0.91        88

    accuracy                           0.90       268
   macro avg       0.90      0.90      0.90       268
weighted avg       0.90      0.90      0.90       268

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_test,
    y_pred
)

print(cm)

[[78  6  8]
 [ 4 82  2]
 [ 3  3 82]]

In [ ]:
sample = X_test.head(10)

predictions = risk_model.predict(sample)

sample['Predicted Risk'] = predictions

sample

/tmp/ipykernel_3018/2044745340.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['Predicted Risk'] = predictions

      age  sex     bmi  children  smoker  region  Predicted Risk
899    49    1  22.515         0       0       0               2
1063   29    0  25.600         4       0       3               1
1255   51    0  36.385         3       0       1               2
298    31    1  34.390         3       1       1               0
237    31    1  38.390         2       0       2               1
481    49    1  37.510         2       0       2               2
240    23    0  36.670         2       1       0               0
277    22    0  24.300         0       0       3               1
415    43    0  35.640         1       0       2               2
706    49    1  28.690         3       0       1               2

In [ ]:
import joblib

joblib.dump(
    risk_model,
    'risk_classifier.pkl'
)

['risk_classifier.pkl']